name: veste_fcm_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.9

dependencies:
  flutter:
    sdk: flutter
  mobx: 2.6.0
  flutter_mobx: 2.3.0
  firebase_core: 4.9.0
  firebase_messaging: 16.2.2
  flutter_local_notifications: 18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: 2.15.0
  mobx_codegen: 2.7.7

flutter:
  uses-material-design: true
